name: macOS builds
permissions: read-all

on:
  push:
    paths-ignore:
      - '.clang-format'
      - '.mdl-styles'
      - '*.md'
      - 'docs/**'
      - 'licenses/**'
      - 'website/**'

  pull_request:
    paths-ignore:
      - '.clang-format'
      - '.mdl-styles'
      - '*.md'
      - 'docs/**'
      - 'licenses/**'
      - 'website/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_macos_release:
    name: Release build (arm64)
    runs-on: macos-15
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Set common vars
        uses: ./.github/actions/set-common-vars

      - name: Set up CMake
        uses: lukka/get-cmake@7bfc9baacbbdcb5e37957ad05c3546b3e222be3c # v4.3.2

      - name: Set up vcpkg
        uses: ./.github/actions/setup-vcpkg
        with:
          name_os: macos-15
          arch: arm64

      - name: Log environment
        run: arch -arch=arm64 ./scripts/ci/log-env.sh

      - name: Build release
        run: |
          set -xo pipefail
          cmake -DOPT_DOCUMENTATION=ON --preset release-macos-arm64
          cmake --build --preset release-macos-arm64 2>&1 | tee build.log

      - name: Run tests
        run: |
          set -xo pipefail
          ctest --preset release-macos-arm64 2>&1 | tee tests.log

      - name: Summarize warnings
        env:
          MAX_WARNINGS: 0
        run: python3 ./scripts/ci/count-warnings.py -lf build.log

      - name: Verify executable RPATH
        run: |
          set -x
          otool -l build/release-macos-arm64/Release/dosbox \
              | grep "path @executable_path/lib"

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: dosbox-arm64
          path: build/release-macos-arm64/Release/dosbox
          overwrite: true
